### PR TITLE
Reference allowedPackage flag: add a specification about the flag telling you can use a specific class name

### PR DESCRIPTION
**Pull request by mbaron**

### CODE REVIEW

**Comment by onigoetz** [comment]
Thanks !

**Comment by npiguet** [comment]
I would actually suggest a better mechanism for that. Why not use ServiceLoader, so that any "reverse-bridge" could explicitly specify which classes it adds support for. This way users of those "reverse-bridges" could just add them to the classpath of their project and automatically be able to use java.util.HashMap or java.util.Whatever without having to alter their project configuration.

**Comment by mbaron** [comment]
Great idea. I'm planning to create a reverse bridge like this to support basic java.util collections (HashMap, ArrayList, HashSet).

I'll be working on it in the next few weeks. When it will be ready, I'll do a PR un st-js project for such support of ServiceProvider for external "allowed packages".

**Comment by acraciun** [comment]
One other way to tell that a STJS lib contains the implementation of some existing classes - that are normally forbiddden, is to add in your final jar (thus in your src/main/resources) a file that tell STJS that this class is allowed. For example for java.util.LinkedList you'll need to have this empty file:
java/util/LinkedList.stjs
(I've just added a test in the generator that tests this).

The advantage of doing like this is that all artifacts importing your library will not need a special configuration in their pom.xml

**Pull request merged**
